const assert=require('node:assert/strict'),{chromium}=require('playwright-core');
const mode=process.argv[2],url=process.argv[3]||'https://holes-and-stars.ichabod-crane.net/';const messages={transform:'whole-mask geometry changes rotate, reflect and scale actual gaps',history:'mask edits undo atomically while probes and rejected edits stay outside history',keep:'a kept mask returns as one reversible edit without changing the inspected spot',profile:'the screen slice plots raw intensity through the inspected spot',link:'the chosen opening identifies its actual arriving wave without changing the sky'};
(async()=>{assert.ok(messages[mode]);const b=await chromium.launch({headless:true,args:['--no-sandbox']});for(const width of[390,1280]){const p=await b.newPage({viewport:{width,height:900},reducedMotion:'reduce'});let errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto(url);
const click=async s=>{const l=p.locator(s);await l.scrollIntoViewIfNeeded();assert.ok(await l.isVisible());await l.click();await p.waitForTimeout(80);};
const points=()=>p.locator('[data-hole-index]').evaluateAll(es=>es.map(e=>({x:Number(e.dataset.x),y:Number(e.dataset.y)})));
const range=async(s,v)=>{await p.locator(s).focus();await p.keyboard.press('Home');const min=Number(await p.locator(s).getAttribute('min')),step=Number(await p.locator(s).getAttribute('step'));for(let i=0;i<Math.round((v-min)/step);i++)await p.keyboard.press('ArrowRight');await p.waitForTimeout(80);};
const pixels=()=>p.locator('#sky').evaluate(e=>Array.from(e.getContext('2d').getImageData(0,0,256,256).data));
const eq=(a,c)=>{assert.equal(a.length,c.length);a.forEach((q,i)=>{assert.ok(Math.abs(q.x-c[i].x)<1e-9);assert.ok(Math.abs(q.y-c[i].y)<1e-9)});};
await click('[data-preset="pair"]');
if(mode==='transform'){let q=await points();await click('#mask-turn-left');eq(await points(),q.map(({x,y})=>({x:-y,y:x})));await click('#mask-reflect');q=await points();await click('#mask-shrink');eq(await points(),q.map(({x,y})=>({x:x*.8,y:y*.8})));await click('#mask-expand');eq(await points(),q);await click('[data-preset="triangle"]');q=await points();await click('#mask-reflect');eq(await points(),q.map(({x,y})=>({x:-x,y})));await click('[data-preset="pair"]');await click('#mask-expand');await click('#mask-expand');await click('#mask-expand');q=await points();await click('#mask-expand');eq(await points(),q);assert.equal(await p.locator('#status').innerText(),'The whole mask has reached the edge.');await click('[data-preset="pair"]');await click('#mask-turn-left');await range('#probe-u',.5);await range('#probe-v',0);assert.equal(await p.locator('#brightness').innerText(),'Brightness: 100%');await range('#probe-v',.5);assert.equal(await p.locator('#brightness').innerText(),'Brightness: 0%');}
if(mode==='history'){assert.ok(await p.locator('#mask-undo').isDisabled());await click('#move-right');const moved=await points();await range('#probe-u',.5);await click('#hole-list button:nth-child(2)');await click('#mask-undo');eq(await points(),[{x:-.5,y:0},{x:.5,y:0}]);assert.equal(await p.locator('#probe-u').inputValue(),'0.5');await click('#mask-redo');eq(await points(),moved);await click('#mask-undo');await click('#remove-hole');assert.ok(await p.locator('#mask-redo').isDisabled());await click('#mask-undo');eq(await points(),[{x:-.5,y:0},{x:.5,y:0}]);await click('#mask-redo');assert.equal((await points()).length,1);await click('#remove-hole');await click('#mask-undo');assert.equal((await points()).length,2);await click('[data-preset="ring"]');await click('#mask-undo');assert.equal((await points()).length,2);const rect=await p.locator('#mask').boundingBox();await p.locator('#mask').scrollIntoViewIfNeeded();const box=await p.locator('#mask').boundingBox();await p.mouse.move(box.x+box.width*.25,box.y+box.height*.5);await p.mouse.down();await p.mouse.move(box.x+box.width*.25+20,box.y+box.height*.5+20,{steps:6});await p.mouse.up();await p.waitForTimeout(80);assert.notDeepEqual(await points(),[{x:-.5,y:0},{x:.5,y:0}]);await click('#mask-undo');eq(await points(),[{x:-.5,y:0},{x:.5,y:0}]);}
if(mode==='keep'){assert.ok(await p.locator('#mask-return').isDisabled());await click('#mask-keep');await click('[data-preset="triangle"]');const q=await points();await range('#probe-u',.5);await click('#mask-return');eq(await points(),[{x:-.5,y:0},{x:.5,y:0}]);assert.equal(await p.locator('#probe-u').inputValue(),'0.5');await click('#mask-undo');eq(await points(),q);await click('#mask-forget');assert.equal(await p.locator('#mask-kept-info').innerText(),'No mask kept.');assert.ok(await p.locator('#mask-return').isDisabled());await click('#mask-redo');assert.equal((await points()).length,2);}
if(mode==='profile'){await click('#screen-slice summary');const check=async()=>{const pts=await points(),v=Number(await p.locator('#probe-v').inputValue());const poly=await p.locator('#slice-line').getAttribute('points');const rows=poly.trim().split(/\s+/).map(s=>s.split(',').map(Number));assert.equal(rows.length,241);rows.forEach(([x,y],i)=>{const u=-6+i*.05;let re=0,im=0;for(const h of pts){const phase=-2*Math.PI*(u*h.x+v*h.y);re+=Math.cos(phase);im+=Math.sin(phase);}const I=(re*re+im*im)/pts.length**2;assert.ok(Math.abs(x-(10+380*i/240))<1e-7);assert.ok(Math.abs(y-(150-140*I))<1e-7);});};await check();await click('[data-preset="triangle"]');await range('#probe-v',.35);await check();await range('#probe-u',.5);assert.ok(Math.abs(Number(await p.locator('#slice-probe').getAttribute('cx'))-(10+6.5*380/12))<1e-7);await click('#move-right');await check();await click('#screen-slice summary');assert.ok(!(await p.locator('#slice-plot').isVisible()));}
if(mode==='link'){const original=await pixels();await click('#hole-list button:nth-child(2)');assert.equal(await p.locator('#wave-diagram [data-wave][data-selected="true"]').getAttribute('data-wave'),'1');assert.equal(await p.locator('#selected-wave-label').innerText(),'Hole 2 arrives on the highlighted arrow.');assert.deepEqual(await pixels(),original);await range('#probe-u',.5);assert.equal(await p.locator('#wave-diagram [data-selected="true"]').count(),1);await click('#remove-hole');assert.equal(await p.locator('#selected-wave-label').innerText(),'Hole 1 arrives on the highlighted arrow.');assert.equal(await p.locator('#wave-diagram [data-wave][data-selected="true"]').getAttribute('data-wave'),'0');}
assert.deepEqual(errors,[]);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`/tmp/holes-depth-${mode}-${width}.png`,fullPage:true});await p.close();}await b.close();console.log(messages[mode]);})().catch(e=>{console.error(e);process.exit(1)});
