const A=require('node:assert/strict'),{chromium}=require('playwright-core');
const mode=process.argv[2],url=process.argv[3];
const audio=()=>{window.__audio={starts:0};class C{constructor(){this.sampleRate=48000;this.destination={};this.currentTime=0}resume(){return Promise.resolve()}createBuffer(c,n,r){const a=new Float32Array(n);return{length:n,duration:n/r,sampleRate:r,getChannelData:()=>a,copyToChannel:s=>a.set(s)}}createBufferSource(){return{connect(){},disconnect(){},start(){__audio.starts++},stop(){}}}}window.AudioContext=C;window.webkitAudioContext=C};
const cases={
"quarterphase":async(p,click,select,check)=>{const old=await p.locator('#mask [data-hole-index]').evaluateAll(es=>es.map(e=>[e.dataset.x,e.dataset.y]));await select('illumination-phase','quarter');A.equal(await p.locator('#brightness').innerText(),'Brightness: 50%');const r=await p.evaluate(async()=>{const m=await import('/model.mjs?oct9='+Date.now());return [m.intensity(m.PRESETS.pair,0,0,{phaseMode:'quarter'}),m.intensity(m.PRESETS.pair,.25,0,{phaseMode:'quarter'}),m.intensity(m.PRESETS.pair,-.25,0,{phaseMode:'quarter'})]});A(Math.abs(r[0]-.5)<1e-12);A(Math.abs(r[1]-1)<1e-12);A(r[2]<1e-28);A.deepEqual(await p.locator('#mask [data-hole-index]').evaluateAll(es=>es.map(e=>[e.dataset.x,e.dataset.y])),old);A(await p.locator('#mask-undo').isDisabled());},
"dimsource":async(p,click,select,check)=>{await select('illumination-strength','alternate-half');A.equal(await p.locator('#brightness').innerText(),'Brightness: 56%');const r=await p.evaluate(async()=>{const m=await import('/model.mjs?oct9='+Date.now());const o={strengthMode:'alternate-half'};return [m.intensity(m.PRESETS.pair,0,0,o),m.intensity(m.PRESETS.pair,.5,0,o),m.field(m.PRESETS.pair,0,0,o).waves]});A.equal(r[0],.5625);A(Math.abs(r[1]-.0625)<1e-12);A.deepEqual(r[2],[{re:1,im:0},{re:.5,im:0}]);A(await p.locator('#mask-undo').isDisabled());await select('illumination-strength','equal');A.equal(await p.locator('#illumination-phase').inputValue(),'equal');}
};
const messages={"quarterphase": "quarter-turn illumination changes cancellation without editing the mask", "dimsource": "half-strength alternate sources reduce brightness without moving any opening"};

(async()=>{A(cases[mode]);const b=await chromium.launch({args:['--no-sandbox']});try{for(const width of [390,1280]){const p=await b.newPage({viewport:{width,height:900},reducedMotion:'reduce'});await p.addInitScript(audio);const errors=[];p.on('pageerror',e=>errors.push(e.message));A.equal((await p.goto(url)).status(),200);await p.waitForTimeout(120);
const reveal=async l=>{const ids=await l.evaluate(e=>{let a=[];for(let n=e.parentElement;n;n=n.parentElement)if(n.tagName==='DETAILS'&&!n.open)a.unshift(n.id);return a});for(const id of ids){A(id);await p.locator('#'+id+'>summary').scrollIntoViewIfNeeded();await p.locator('#'+id+'>summary').click()}};
const click=async id=>{const l=p.locator('#'+id);await reveal(l);await l.scrollIntoViewIfNeeded();A(await l.isEnabled(),id+' enabled');A(await l.evaluate(e=>{const r=e.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return h===e||e.contains(h)}),id+' hit');await l.click();await p.waitForTimeout(70)};
const select=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.selectOption(v);await p.waitForTimeout(70)};
const check=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.setChecked(v);await p.waitForTimeout(70)};
await cases[mode](p,click,select,check);A.deepEqual(errors,[]);A(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`/tmp/planner-oct9-${mode}-${width}.png`,fullPage:true});await p.close();}console.log(messages[mode]);}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
