const A=require('node:assert/strict'),{chromium}=require('playwright-core');
const mode=process.argv[2],url=process.argv[3];
const cases={
rectangle:async(p,click,select)=>{await select('#opening-shape','wide');await p.waitForFunction(()=>document.querySelector('#brightness').textContent.includes('100%'));const r=await p.evaluate(async()=>{const m=await import('/model.mjs?plannerpm='+Date.now());const o={width:.5,height:.1};const a=m.field(m.PRESETS.pair,1,0,o);return {one:a.intensity,zero:m.intensity(m.PRESETS.pair,2,0,o),peak:m.intensity(m.PRESETS.pair,0,0,o),plain:m.intensity(m.PRESETS.pair,1,0),wave:a.waves[0].re};});A.ok(Math.abs(r.one-4/Math.PI**2)<1e-12);A.ok(r.zero<1e-28);A.equal(r.peak,1);A.equal(r.plain,1);A.ok(Math.abs(r.wave+2/Math.PI)<1e-12);await p.locator('#probe-u').press('Home');await p.locator('#probe-u').press('ArrowRight',{pressDelay:0});await select('#opening-shape','point');A.equal(await p.locator('#opening-shape').inputValue(),'point');},
phase:async(p,click,select)=>{await select('#illumination-phase','alternate');await p.waitForFunction(()=>document.querySelector('#brightness').textContent==='Brightness: 0%');const r=await p.evaluate(async()=>{const m=await import('/model.mjs?plannerpm='+Date.now());return [m.intensity(m.PRESETS.pair,0,0,{phaseMode:'alternate'}),m.intensity(m.PRESETS.pair,.5,0,{phaseMode:'alternate'}),m.field(m.PRESETS.pair,0,0,{phaseMode:'alternate'}).waves];});A.ok(r[0]<1e-28);A.equal(r[1],1);A.equal(r[2][0].re,1);A.equal(r[2][1].re,-1);await select('#illumination-phase','equal');await p.waitForFunction(()=>document.querySelector('#brightness').textContent==='Brightness: 100%');},
solo:async(p,click,select)=>{await select('#illumination-holes','chosen');await p.waitForFunction(()=>document.querySelector('#brightness').textContent==='Brightness: 25%');await click('hole-list button:nth-child(2)',true);await p.waitForTimeout(80);A.equal(await p.locator('#brightness').innerText(),'Brightness: 25%');const r=await p.evaluate(async()=>{const m=await import('/model.mjs?plannerpm='+Date.now());return [m.field(m.PRESETS.pair,1.2,.4,{onlyIndex:1}),m.intensity(m.PRESETS.pair,0,0,{onlyIndex:0})];});A.equal(r[0].waves[0].re,0);A.equal(r[0].waves[0].im,0);A.ok(Math.abs(r[0].intensity-.25)<1e-12);A.equal(r[1],.25);await select('#illumination-holes','all');await p.waitForFunction(()=>document.querySelector('#brightness').textContent==='Brightness: 100%');},
keptslice:async(p,click,select)=>{await click('mask-keep');await click('mask-shrink');await click('slice-show-kept');await p.waitForTimeout(80);A.equal(await p.locator('#slice-kept-line').getAttribute('hidden'),null);const a=await p.locator('#slice-line').getAttribute('points'),b=await p.locator('#slice-kept-line').getAttribute('points');A.notEqual(a,b);await click('mask-return');await p.waitForTimeout(80);A.equal(await p.locator('#slice-line').getAttribute('points'),await p.locator('#slice-kept-line').getAttribute('points'));await click('mask-forget');A.ok(await p.locator('#slice-show-kept').isDisabled());A.ok(!(await p.locator('#slice-show-kept').isChecked()));A.notEqual(await p.locator('#slice-kept-line').getAttribute('hidden'),null);}
};
const messages={rectangle:'rectangular opening size shapes an envelope without moving the mask',phase:'opposite illumination moves a bright center to cancellation without moving holes',solo:'one chosen opening stays on the complete mask brightness scale',keptslice:'a kept mask shares the live row and intensity scale without replacing it'};
(async()=>{A.ok(cases[mode]);const b=await chromium.launch({args:['--no-sandbox']});for(const width of[390,1280]){const p=await b.newPage({viewport:{width,height:900}});const errors=[];p.on('pageerror',e=>errors.push(String(e)));A.equal((await p.goto(url)).status(),200);await p.waitForTimeout(100);const click=async(id,css=false)=>{const l=p.locator(css?'#'+id:'#'+id);const ds=await l.evaluate(e=>{let a=[];for(let x=e.parentElement;x;x=x.parentElement)if(x.tagName==='DETAILS'&&!x.open)a.unshift(x.id);return a});for(const d of ds)await p.locator('#'+d+'>summary').click();await l.scrollIntoViewIfNeeded();const bb=await l.boundingBox();A.ok(bb);A.ok(await l.evaluate(e=>{const r=e.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return h===e||e.contains(h)}));await l.click();};const select=async(s,v)=>{const l=p.locator(s);const ds=await l.evaluate(e=>{let a=[];for(let x=e.parentElement;x;x=x.parentElement)if(x.tagName==='DETAILS'&&!x.open)a.unshift(x.id);return a});for(const d of ds)await p.locator('#'+d+'>summary').click();await l.selectOption(v);await p.waitForTimeout(80)};await cases[mode](p,click,select);A.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));A.deepEqual(errors,[]);await p.screenshot({path:`/tmp/holes-pm-${mode}-${width}.png`,fullPage:true});await p.close()}await b.close();console.log(messages[mode])})().catch(e=>{console.error(e);process.exit(1)});
