const A=require('node:assert/strict'),{chromium}=require('playwright-core');
const mode=process.argv[2],url=process.argv[3]||'https://holes-and-stars.ichabod-crane.net/';
const messages={center:'centering a mask moves its phase arrows without changing its interference',axis:'one screen slice can cross the spot horizontally or vertically',arrays:'three four-hole masks distinguish equal gaps a broken gap and two axes'};
async function reveal(p,s){const ids=await p.locator(s).evaluate(e=>{let a=[];for(let x=e.parentElement;x;x=x.parentElement)if(x.tagName==='DETAILS'&&!x.open)a.unshift(x.id);return a;});for(const id of ids){const q=p.locator('#'+id+'>summary');await q.scrollIntoViewIfNeeded();await q.click();}}
async function click(p,s){await reveal(p,s);const e=p.locator(s);await e.scrollIntoViewIfNeeded();A(await e.isEnabled());A(await e.evaluate(e=>{const r=e.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return h===e||e.contains(h)}));await e.click();}
async function range(p,s,v){await reveal(p,s);const e=p.locator(s);await e.focus();await p.keyboard.press('Home');const min=Number(await e.getAttribute('min')),step=Number(await e.getAttribute('step'));for(let i=0;i<Math.round((v-min)/step);i++)await p.keyboard.press('ArrowRight');await p.waitForTimeout(150);}
async function points(p){return p.locator('[data-hole-index]').evaluateAll(es=>es.map(e=>({x:Number(e.dataset.x),y:Number(e.dataset.y)})));}
async function waitPoints(p,want){await p.waitForFunction(w=>JSON.stringify([...document.querySelectorAll('[data-hole-index]')].map(e=>({x:Number(e.dataset.x),y:Number(e.dataset.y)})))===JSON.stringify(w),want,{polling:30});}
(async()=>{A(messages[mode]);const b=await chromium.launch({args:['--no-sandbox']});try{for(const width of[390,1280]){const p=await b.newPage({viewport:{width,height:900},reducedMotion:'reduce'});let errors=[];p.on('pageerror',e=>errors.push(e.message));A.equal((await p.goto(url)).status(),200);
if(mode==='center'){A(await p.locator('#mask-center').isDisabled());await click(p,'#move-right');await click(p,'#move-right');await click(p,'#move-right');await range(p,'#probe-u',.35);await p.waitForTimeout(250);const before=await points(p);const brightness=await p.locator('#brightness').innerText();const pixels=await p.locator('#sky').evaluate(e=>Array.from(e.getContext('2d').getImageData(0,0,256,256).data));await click(p,'#mask-center');await waitPoints(p,[{x:-.5,y:0},{x:.5,y:0}]);await p.waitForTimeout(250);A.equal(await p.locator('#brightness').innerText(),brightness);A.equal(await p.locator('#probe-u').inputValue(),'0.35');const after=await p.locator('#sky').evaluate(e=>Array.from(e.getContext('2d').getImageData(0,0,256,256).data));A(pixels.every((v,i)=>Math.abs(v-after[i])<=1));A(await p.locator('#mask-center').isDisabled());await click(p,'#mask-undo');A.deepEqual(await points(p),before);await click(p,'#mask-redo');await waitPoints(p,[{x:-.5,y:0},{x:.5,y:0}]);}
if(mode==='axis'){await reveal(p,'#slice-axis');A.equal(await p.locator('#slice-axis').inputValue(),'row');await click(p,'[data-preset="triangle"]');await range(p,'#probe-u',.35);await range(p,'#probe-v',.2);for(const axis of['row','column']){await p.selectOption('#slice-axis',axis);await p.waitForTimeout(180);const pts=await points(p);const got=(await p.locator('#slice-line').getAttribute('points')).split(/\s+/).map(s=>s.split(',').map(Number));A.equal(got.length,241);for(let i=0;i<241;i++){const s=-6+i*.05,u=axis==='row'?s:.35,v=axis==='row'?.2:s;let re=0,im=0;for(const q of pts){const phase=-2*Math.PI*(u*q.x+v*q.y);re+=Math.cos(phase);im+=Math.sin(phase);}const I=Math.max(0,Math.min(1,(re*re+im*im)/pts.length**2));A(Math.abs(got[i][0]-(10+380*i/240))<1e-7);A(Math.abs(got[i][1]-(150-140*I))<1e-7);}const coordinate=axis==='row'?.35:.2;A(Math.abs(Number(await p.locator('#slice-probe').getAttribute('cx'))-(10+(coordinate+6)*380/12))<1e-7);A.equal(await p.locator('#slice-direction').innerText(),axis==='row'?'Left to right':'Bottom to top');}A.equal(await p.locator('#probe-u').inputValue(),'0.35');A.equal(await p.locator('#probe-v').inputValue(),'0.2');}
if(mode==='arrays'){const data={row:[{x:-.6,y:0},{x:-.2,y:0},{x:.2,y:0},{x:.6,y:0}],broken:[{x:-.6,y:0},{x:-.2,y:0},{x:.2,y:0},{x:.8,y:0}],square:[{x:-.4,y:-.4},{x:.4,y:-.4},{x:.4,y:.4},{x:-.4,y:.4}]};for(const id of['row','broken','square']){await click(p,`[data-preset="${id}"]`);await waitPoints(p,data[id]);A.equal(await p.locator('#hole-count').innerText(),'4 of 8 holes');await range(p,'#probe-u',.5);await range(p,'#probe-v',0);const expected=(()=>{let re=0,im=0;for(const q of data[id]){const phi=-2*Math.PI*.5*q.x;re+=Math.cos(phi);im+=Math.sin(phi);}return `Brightness: ${Math.round(100*(re*re+im*im)/16)}%`;})();A.equal(await p.locator('#brightness').innerText(),expected);}await click(p,'#mask-undo');A.deepEqual(await points(p),data.broken);await click(p,'#mask-redo');A.deepEqual(await points(p),data.square);}
A.deepEqual(errors,[]);A(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`/tmp/holes-evening-${mode}-${width}.png`,fullPage:true});await p.close();}console.log(messages[mode]);}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
